### ISSUE TITLE
allow hiding Superuser commands

### ISSUE THREAD

**Issue by jidanni** [kwattsorg/adbshellkit#12]
Maybe add an option to hide the commands that requires Superuser.

**Comment by kwatkins** [comment]
Yep, another good feature I had planned on. Getting the ability to tag and identify commands that need it is done, at least. 

The workflow would be having this as an option, "Hide commands requiring superuser" and possibly "Hide commands requiring elevated permissions" - and if root is not detected, it will hide those commands, otherwise display them.

**Comment by jidanni** [comment]
Yes there are several levels, real root only commands, and then commands
that non-root users have turned on via adb pm on manifest items, and
then regular commands.

Or like the Unix (Linux) manual sections, let's say you don't want to
see section 6, games... so maybe have a checklist of what tagged items
to show / not show.

**Comment by alialooooosh055455** [comment]
:smile:

**Comment by kwatkins** [comment]
@jidanni added, although have it as default to not hide superuser commands - if root isn't detected of course. Do you think hiding superuser commands if root isn't detected on by default?

**Comment by jidanni** [comment]
OK, as long as the user can find where to toggle it easily in Settings.

**Comment by kwatkins** [comment]
Cool, added and released to beta. Will hit production soon, making sure there isn't crashes etc in the betapool
