### ISSUE TITLE
 put more permissions in the Manifest

### ISSUE THREAD

**Issue by jidanni** [kwattsorg/adbshellkit#13]
Put more permissions in your manifest, and then we could turn them on using ADB, and then be able to use logcat Etc without root.

**Comment by jidanni** [comment]
Of course in the about section you would have to mention how the user can turn them on with ADB.

**Comment by jidanni** [comment]
That is how https://github.com/plusCubed/matlog
does it.

**Comment by kwatkins** [comment]
Ahh, lots of good suggestions @jidanni - will try and get through these! 

I do plan to add more permissions. Will need since runtime permission checks can now be added to commands and need to be in the manifest as well. 

Downside is might turn people off on Google Play, so need to describe why the commands are there and that they won't be activated or requested until the user tries to run a command that needs 'em. 

Ahh, your also right about adb shell user has perms to the package manager and can enable commands. In the help/about section, or better yet, at runtime when a command needs a permission and it isn't found, the steps to enable it with adb would popup (or even a simple toast message pointing to the about section). If you/someone else wants to pick up adding this to the about/help section and git pull I'll do the merge.
